lib/proyecto3_web/router.ex
defmodule Proyecto3Web.Router do
  use Proyecto3Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Proyecto3Web do
    pipe_through :browser

    resources "/posts", PostController
    resources "/register", UserController, only: [:new, :create]
    get "/", PostController, :index

    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
    
  end

  # Other scopes may use custom stacks.
  # scope "/api", Proyecto3Web do
  #   pipe_through :api
  # end
end

lib/proyecto3_web/views/layout_view.ex
defmodule Proyecto3Web.LayoutView do
  use Proyecto3Web, :view
end

lib/proyecto3_web/templates/layout/_card.html.eex
<link href="https://bootswatch.com/4/lux/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

lib/proyecto3_web/templates/layout/_navbar.html.eex
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Thoughts</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" >
      <li class="nav-item" >
        <a class="nav-link"><%= link "Posts", to: Routes.post_path(@conn, :index) %></a>     
      </li>
      
      <li class="nav-item">
        <a class="nav-link" >
        <%= if signed_in?(@conn) do %>
          <%= link "Cerrar Sesión", to: Routes.session_path(@conn, :delete), method: :delete%> 
        <% else %>
          <%= link "Iniciar Sesión", to: Routes.session_path(@conn, :new) %>
          |
          <%= link "Registrarse", to: Routes.user_path(@conn, :new) %>
        <% end %>
        </a>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= if signed_in?(@conn) do %>
        <img src="<%= Plug.Conn.get_session(@conn, :current_img) %>" alt="Img" height="42" width="42" style="border-radius: 1000px;">
        <h1 class="navbar-brand" style="margin-left: 10px;"><%= Plug.Conn.get_session(@conn, :current_username) %></h1>
      <% end %>
    </form>
  </div>
</nav>
<br><br>

lib/proyecto3_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://bootswatch.com/4/lux/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
    <title>Proyecto3 · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

  </head>
  <body>
    <%=render "_navbar.html",conn: @conn %>
    
    <main role="main" class="container">
      
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>